### ISSUE TITLE
WARNING: Can not map type for xxx, insert operation skipped.

### ISSUE THREAD

**Issue by franckvallee** [andbi/evrete#15]
When a service is loaded from a JAVA dsl source that is not compiled within the mainstream project (but a file copy is extracted from it at build time):

> service.newKnowledge( "JAVA-SOURCE", new File("rulesets/MyRS.java").toURI().toURL());

When MyRS.java refers to a type that is regularly imported  within the mainstream project!

> import com.ffvatrades.pm.strategy.dto.DayTrendFact;
>...
> @Rule( salience=PRIORITY_A )
   public void initMACD( DayTrendFact $x, RhsContext ctx) {
   ...
}

Then DayTrendFact class is reported as not mapped:
 >Jun 12, 2022 7:56:34 PM org.evrete.runtime.AbstractRuleSession insertAtomic
WARNING: Can not map type for 'com.ffvatrades.pm.strategy.dto.DayTrendFact', insert operation skipped.

But when I want to declare this class upfront, I've an IllegalStateException reporting the class is already declared.

**Comment by andbi** [comment]
I can not reproduce the issue. Could you please have a look at the test I've just committed
Test: https://github.com/andbi/evrete/blob/master/evrete-dsl-java/src/test/java/org/evrete/dsl/issues/IssuesTests.java
Ruleset: https://github.com/andbi/evrete/blob/master/evrete-dsl-java/src/test/resources/java/issues/MyRS.java

, and tell me how it is  different to what you're trying to achieve?

The test passes w/o any exceptions and the `DayTrendFact` facts get processed as expected.

**Comment by franckvallee** [comment]
Sorry, I was on it and later discovered something I didn't mentioned (because this was not in my mind).
DayTrendFact is declared as Java 14 record and not as a class.
This is certainly what makes the difference.

**Comment by franckvallee** [comment]
Unfortunately after having moved DayTrendFact from record into classical POJO class, this doesn't fix the issue.

**Comment by andbi** [comment]
The engine supports Java records from day one because records are also classes. I personally haven't tested them in Java 14 (records still in incubator) but since Java 16 I saw no problems feeding them into Evrete rule sessions.

Is it possible to create a simple project that would reproduce the bug?

**Comment by franckvallee** [comment]
Difficult to reproduce the bug because I've started from a small POC project first that worked fine before going to integrate EVRETE in a larger project and there the problem raised.
My dependency is:
>    // https://mvnrepository.com/artifact/org.evrete/evrete-core
    implementation group: 'org.evrete', name: 'evrete-core', version: '2.2.01'

What I can see in debugging is that com.ffvatrades.pm.strategy.dto.DayTrendFact is a plain class without ancestor.
In class DefaultTypeResolver:
>#198 returns null: ArrayOf<Type<?>> associatedTypes = typesByJavaType.get(name);

Then
>#208 returns null: TypeCacheEntry cacheEntry = typeInheritanceCache.get(name);

And finally
>#218 returns null: return (TypeImpl<T>) cacheEntry.type;

The name has correct value (i.e. the plain java class name and package path), but it is not correctly registered in the Map called typesByJavaType.

**Comment by franckvallee** [comment]
Here's the stack when called the constructor of DefaultTypeResolver
>DefaultTypeResolver.<init>:44	
DefaultTypeResolver.copyOf:224	
DefaultTypeResolver.copyOf:11	
RuntimeMetaData.<init>:37	
AbstractRuntime.<init>:46	
AbstractRuleSession.<init>:38	
AbstractRuleSessionIO.<init>:15	
StatelessSessionImpl.<init>:13	
KnowledgeRuntime.newStatelessSession:77	
KnowledgeService.newStatelessSession:279	
DayTrendEvaluator.evaluateDayTrendAt:42	
DayTrendEvaluator.evaluateDayTrend:48	
TradingDetectorTest.DetectorAndDayTrendTest:28

**Comment by franckvallee** [comment]
The default type resolved is constructed by the copy of one another in which all Java Type collections are already empty.

**Comment by franckvallee** [comment]
Eventually when the resolve method is called, all java types collection of the Resolver are empty.
![image](https://user-images.githubusercontent.com/44505738/173254053-d75f4d90-4b3c-4328-926a-a42069fc5604.png)

**Comment by andbi** [comment]
As a workaround, you may stop declaring the class upfront and a) try calling the `addImport` method on a`Configuration` or `Knowledge` instance to add the "missing" type, or  b) setting the class loader explicitly in the `Configuration`. But that would be just a workaround and wouldn't help resolving the issue if it really exists.

Otherwise I'm afraid I will need a minimal reproducible example: https://stackoverflow.com/help/minimal-reproducible-example  

I appreciate the provided data, but it's clearly not enough to tell whether it's a bug in the library or a developer's mistake/oversight.

**Comment by franckvallee** [comment]
I've found the issue.
Comparing to my POC, I've discorvered the sequence RS.newStatelessSession().insertAndFire(fact);
was called against RS as a KnowledgeService instead RS as a Knowledge.
